name: Nyx AI Code Review
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ Enables repo access

    steps:
      - name: 🛠 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔍 Fetch Repository Contents for Nyx AI
        run: |
          curl -X GET "https://api.github.com/repos/CPADelaney/project_nyx/contents" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json"

      - name: 🚀 Allow Nyx to Modify Code (Optional)
        run: |
          curl -X PATCH "https://api.github.com/repos/CPADelaney/project_nyx" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"description": "Updating repository details via Nyx AI."}'
